#!/usr/bin/env sh

# Disable status bar, and add space for spacehar
yabai -m config status_bar                   off
yabai -m config top_padding                  26

# Global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          4
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# General space settings
yabai -m config layout                       bsp
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# Program specific settings
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^KeePassXC$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^.*Zoom.*$" manage=off
yabai -m rule --add app="^Microsoft Teams$" manage=off
yabai -m rule --add app="^Installer$" manage=off

yabai -m rule --add title=".*Mayavi Scene.*" manage=off
yabai -m rule --add title=".*Eve Main Window.*" manage=off
yabai -m rule --add title="^Opening .*$" manage=off
yabai -m rule --add title="^Copy$" manage=off

yabai -m rule --add title="Preferences$" manage=off topmost=on
yabai -m rule --add title="Picture-In-Picture$" manage=off topmost=on
