#!/usr/bin/env sh

# Load the Yabai scripting addon
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Forward events to sketchybar
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_changed &> /dev/null"

yabai -m signal --add event=window_created action="sketchybar -m --trigger window_created &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger window_destroyed &> /dev/null"

yabai -m signal --add event=mission_control_exit action="sketchybar -m --trigger mission_control_exit &> /dev/null"

# Define the height of sketchybar
yabai -m config external_bar all:33:0

# Global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          4
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config window_origin_display        cursor

# General space settings
yabai -m config layout                       bsp
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# Program specific settings

# System
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add title="^Opening .*$" manage=off
yabai -m rule --add title="^Copy$" manage=off
yabai -m rule --add title="Preferences$" manage=off topmost=on

# Social
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^.*Mattermost.*$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^.*Zoom.*$" manage=off
yabai -m rule --add app="^.*zoom.*$" manage=off
yabai -m rule --add app="^Microsoft Teams$" manage=off

# Utility
yabai -m rule --add title="^.*KeePassXC.*$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^.*Arduino.*$" manage=off
yabai -m rule --add app="^.*Stick.*$" manage=off
yabai -m rule --add title="Picture-In-Picture$" manage=off topmost=on

# Work
yabai -m rule --add app="^.*Outlook.*$" manage=off
yabai -m rule --add app="^.*root.exe.*$" manage=off
yabai -m rule --add title=".*Mayavi.*" manage=off
yabai -m rule --add title=".*Eve Main Window.*" manage=off

# Graphics
yabai -m rule --add app="^.*GIMP.*$" manage=off
yabai -m rule --add app="^.*Inkscape.*$" manage=off

yabai -m rule --add app=".*" sub-layer=normal
